# -*- coding: utf-8 -*-
"""Statistics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PZPycfdgSeQfazBJTeayAR-g1CFmx-Ws
"""

#Program to find Mean
numbers = [10, 20, 30, 40, 50]
mean = sum(numbers) / len(numbers)
print("Mean =", mean)

# Program to find Median
numbers = [10, 20, 30, 40, 50]
numbers.sort()
n = len(numbers)
if n % 2 == 0:
    median = (numbers[n//2 - 1] + numbers[n//2]) / 2
else:
    median = numbers[n//2]
print("Median =", median)

# Program to find Mode
numbers = [10, 20, 20, 30, 40, 20, 50]
mode = max(set(numbers), key=numbers.count)
print("Mode =", mode)

# Program to find Variance
numbers = [10, 20, 30, 40, 50]
mean = sum(numbers) / len(numbers)
variance = sum((x - mean) ** 2 for x in numbers) / len(numbers)
print("Variance =", variance)

# Program to find Standard Deviation
numbers = [10, 20, 30, 40, 50]
mean = sum(numbers) / len(numbers)
variance = sum((x - mean) ** 2 for x in numbers) / len(numbers)
std_deviation = variance ** 0.5
print("Standard Deviation =", std_deviation)

# Program to compute Mean, Median, Mode, Variance, and Standard Deviation
import statistics
# Input numbers from user
data = list(map(float, input("Enter numbers separated by space: ").split()))
# Mean
mean = statistics.mean(data)
# Median
median = statistics.median(data)
# Mode
try:
    mode = statistics.mode(data)
except statistics.StatisticsError:
    mode = "No unique mode"
# Variance
variance = statistics.variance(data)
# Standard Deviation
std_dev = statistics.stdev(data)
# Display Results
print("\n----- Statistical Measures -----")
print("Mean =", mean)
print("Median =", median)
print("Mode =", mode)
print("Variance =", variance)
print("Standard Deviation =", std_dev)